admin_perpus/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'admin_perpus'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name= 'admin_perpus/login.html'), name='login'),
    path('pilihanCrud/', views.pilihanCrud, name='pilihanCrud' ),
    path('formCrudCatalog/', views.formCrudCatalog, name='formCrudCatalog'),                # get and post req. insert operation
    path('formCrudCatalog/<int:id>/', views.formCrudCatalog, name='formCrudCatalogUpdate'), # get and post req. update operation
    path('catalogList/', views.catalogList, name='catalogList'),                            # get req. to retrieve and display all record
    path('catalogDelete/<int:id>/', views.catalogDelete, name='catalogDelete'),
    path('formCrudJurnal/', views.formCrudJurnal, name='formCrudJurnal'),
    path('formCrudJurnal/<int:id>', views.formCrudJurnal, name='formCrudJurnalUpdate'),
    path('jurnalList/', views.jurnalList, name='jurnalList'),
    path('jurnalDelete/<int:id>/', views.jurnalDelete, name='jurnalDelete'),
    path('formCrudRepository/', views.formCrudRepository, name='formCrudRepository'),
    path('formCrudRepository/<int:id>', views.formCrudRepository, name='formCrudRepositoryUpdate'),
    path('repositoryList/', views.repositoryList, name='repositoryList'),
    path('repositoryDelete/<int:id>/', views.repositoryDelete, name='repositoryDelete')
]

layanan/urls.py
from django.urls import path
from layanan.views import *

app_name = 'layanan'
urlpatterns = [
    path('catalog/', catalogListView.as_view(), name='catalog'),
    path('repository/', repositoryListView.as_view(), name="repository"),
    path('repositoryDetail/<slug:slug>/', repositoryDetailView.as_view(), name='repository_detail'),
    path('journal/', journalListView.as_view(), name="journal"),
    path('journalDetail/<slug:slug>/', journalDetailView.as_view(), name='journal_detail'),
]

perpustakaan/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    path('profil/', include('profil.urls')),
    path('petunjuk/', include('petunjuk.urls')),
    path('layanan/', include('layanan.urls')),
    path('admin_perpus/', include('admin_perpus.urls'))
]

petunjuk/urls.py
from django.urls import path
from petunjuk.views import *

app_name = 'petunjuk'
urlpatterns = [
    path('petunjuk-perpustakaan', petunjukPerpustakaan, name="petunjuk-perpustakaan"),
    path('peminjamanpengembalian-buku', peminjamanBuku, name="peminjaman-buku"),
]

profil/urls.py
from django.urls import path
from profil.views import *

app_name = "profil"
urlpatterns = [
    path('profil-perpustakaan/', profilPerpustakaan, name="profil-perpustakaan"),
    path('layanan-perpustakaan/', layananPerpustakaan, name="layanan-perpustakaan"),
]

templates/snippets/navbar.html
{% load static %}

<style>
  .bg-light {
    background-color: #fff !important;
  }

  .nav-link {
    color: #004B84!important;
    border-bottom: 0.5px solid transparent !important;
  }

  .nav-link:hover {
    border-bottom: 0.5px solid #004B84!important;
  }

  .navbar-nav {
    font-family: 'Roboto', sans-serif;
  }

  .dropdown-menu {
    font-family: 'Roboto', sans-serif !important;
  }

  .dropdown-item {
    color: #004B84!important;
    background-color: transparent;
    border-bottom: 0.5px solid transparent !important;
  }

  .dropdown-item:hover {
    border-bottom: 0.5px solid #004B84!important;
    background: transparent;
  }
  
</style>

<nav class="navbar fixed-top fixed-effect navbar-expand-lg navbar-light bg-light shadow">
    <div class="container-fluid px-5">
      <a class="navbar-brand" href="#">
        <img src="{% static 'img/uhamka.png'%}" alt="logo uhamka" style="height: 70px;">
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0 fw-bold">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="/">Beranda</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Profil
            </a>
            <ul class="dropdown-menu shadow" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{% url 'profil:profil-perpustakaan' %}">Profil Perpustakaan</a></li>
              <li><a class="dropdown-item" href="{% url 'profil:layanan-perpustakaan' %}">Layanan Perpustakaan</a></li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Layanan
            </a>
            <ul class="dropdown-menu shadow" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{% url 'layanan:journal' %}">Journal</a></li>
              <li><a class="dropdown-item" href="{% url 'layanan:repository' %}">Repository</a></li>
              <li><a class="dropdown-item" href="{% url 'layanan:catalog' %}">Catalog</a></li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Petunjuk
            </a>
            <ul class="dropdown-menu shadow" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{% url 'petunjuk:petunjuk-perpustakaan' %}">Petunjuk Perpustakaan</a></li>
              <li><a class="dropdown-item" href="{% url 'petunjuk:peminjaman-buku' %}">Peminjaman/Pengembalian Buku</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin_perpus:login' %}"><i class="fa fa-sign-in-alt"></i> Login</a>
          </li>
      </div>
    </div>
  </nav>

templates/snippets/scripts.html
{% load static %}

<script src="{% static 'vendor/bundle/bundle.js' %}" type="text/javascript"></script>
<script src="{% static 'js/effectscard.js' %}" type="text/javascript"></script>
<script src="{% static 'js/particles.js' %}" type="text/javascript"></script>
<script src="{% static 'js/app.js' %}" type="text/javascript"></script>

templates/snippets/styles.html
{% load static %}

<link rel="stylesheet" href="{% static 'vendor/bootstrap/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'vendor/font-awesome/font-awesome.css' %}">