admin_perpus/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'admin_perpus'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name= 'admin_perpus/login.html'), name='login'),
    path('pilihanCrud/', views.pilihanCrud, name='pilihanCrud' ),
    path('formCrudCatalog/', views.formCrudCatalog, name='formCrudCatalog'),                # get and post req. insert operation
    path('formCrudCatalog/<int:id>/', views.formCrudCatalog, name='formCrudCatalogUpdate'), # get and post req. update operation
    path('catalogList/', views.catalogList, name='catalogList'),                            # get req. to retrieve and display all record
    path('catalogDelete/<int:id>/', views.catalogDelete, name='catalogDelete'),
    path('formCrudJurnal/', views.formCrudJurnal, name='formCrudJurnal'),
    path('formCrudJurnal/<int:id>', views.formCrudJurnal, name='formCrudJurnalUpdate'),
    path('jurnalList/', views.jurnalList, name='jurnalList'),
    path('jurnalDelete/<int:id>/', views.jurnalDelete, name='jurnalDelete'),
    path('formCrudRepository/', views.formCrudRepository, name='formCrudRepository'),
    path('formCrudRepository/<int:id>', views.formCrudRepository, name='formCrudRepositoryUpdate'),
    path('repositoryList/', views.repositoryList, name='repositoryList'),
    path('repositoryDelete/<int:id>/', views.repositoryDelete, name='repositoryDelete')
]

perpustakaan/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    path('profil/', include('profil.urls')),
    path('petunjuk/', include('petunjuk.urls')),
    path('layanan/', include('layanan.urls')),
    path('admin_perpus/', include('admin_perpus.urls'))
]

profil/urls.py
from django.urls import path
from profil.views import *

app_name = "profil"
urlpatterns = [
    path('profil-perpustakaan/', profilPerpustakaan, name="profil-perpustakaan"),
    path('layanan-perpustakaan/', layananPerpustakaan, name="layanan-perpustakaan"),
]

admin_perpus/models.py
from django.db import models
# Create your models here.

# catalog 

# journal 

# repository

# buku

admin_perpus/forms.py
from django.forms import ModelForm
from django import forms
from layanan.models import *

class formCatalog(forms.ModelForm):
    class Meta:
        model = catalog
        fields = '__all__'  
    
    def __init__(self, *args, **kwargs):
        super(formCatalog,self).__init__(*args, **kwargs)
        self.fields['bahasa'].empty_label = "Select"
        # self.fields['jumlah_buku'].required = False
 
class formJournal(forms.ModelForm):
    class Meta:
        model = journal
        fields = '__all__' 

class formRepository(forms.ModelForm):
    class Meta:
        model = repository
        fields = '__all__' 

admin_perpus/views.py
from django.shortcuts import render, redirect
from layanan.models import *  # import database
from django.contrib.auth import views as auth_views
from layanan.forms import *  # import form terima data
from .forms import *

# Create your views here.


def admin_perpus(request):
    context = {
        'title': 'Perpustakaan'
    }
    return render(request, 'admin_perpus/login.html', context)


def pilihanCrud(request):
    greeting = 'selamat datang'
    context = {
        'title': 'Form CRUD',
        'ucapan': greeting
    }
    return render(request, 'admin_perpus/pilihanCrud.html', context)

# ======================================================================


def catalogList(request):
    data = catalog.objects.all()
    context = {
        'catalog_list': data

    }
    return render(request, 'admin_perpus/listCatalog.html', context)


def formCrudCatalog(request, id=0):
    if request.method == 'GET':
        # input pertama user -> id data = 0
        if id == 0:
            form = formCatalog()
        # kalau datanya diambil dari db -> id data != 0
        else:
            updateCatalog = catalog.objects.get(pk=id)
            form = formCatalog(instance=updateCatalog)
        context = {
            'title': 'Catalog',
            'form': form,
            'namaMethod': "formCrudCatalog(if)"
        }
        return render(request, "admin_perpus/formCrudCatalog.html", context)

    else:
        form = formCatalog(request.POST)
        if form.is_valid():
            form.save()

        return redirect('catalogList/')


def catalogDelete(request, id):
    deleteCatalog = catalog.objects.get(pk=id)
    deleteCatalog.delete()
    return redirect('catalogList/')

# -------------------------------------------------------------------------------


def jurnalList(request):
    data = journal.objects.all()

    context = {
        'journal_list': data,
        'namaMethod': "jurnalList"
    }
    return render(request, 'admin_perpus/listJurnal.html', context)


def formCrudJurnal(request, id=0):
    if request.method == 'GET':
        if id == 0:
            form = formJournal()
        else:
            updateJurnal = journal.objects.get(pk=id)
            form = formJournal(instance=updateJurnal)

        context = {
            'title': 'Jurnal',
            'form': form,
            'namaMethod': "formCrudJurnal(if)"
        }
        return render(request, "admin_perpus/formCrudJournal.html", context)

    else:
        form = formJournal(request.POST)
        if form.is_valid():
            form.save()
            context = {
                'namaMethod': 'formCrudJurnal(else)'
            }
        return redirect('jurnalList/')


def jurnalDelete(request, id):
    deleteJurnal = jurnal.objects.get(pk=id)
    deleteJurnal.delete()
    return redirect('jurnalList/')

# --------------------------------------------------------------------------------


def repositoryList(request):
    data = repository.objects.all()

    context = {
        'repository_list': data,
        'namaMethod': "repositoryList"
    }
    return render(request, 'admin_perpus/repositoryList.html', context)


def formCrudRepository(request, id=0):
    if request.method == 'GET':
        if id == 0:  # we have an insert operation
            form = formRepository()
        else:  # update operation
            updateRepository = repository.objects.get(pk=id)
            form = formRepository(instance=updateRepository)

        context = {
            'title': 'Repository',
            'form': form,
            'namaMethod': "formRepository(if)"
        }
        return render(request, "admin_perpus/formCrudRepository.html", context)

    # post request
    else:
        if id == 0:  # masukan pertama kali
            form = formRepository(request.POST)
        else:  # update
            updateRepository = repository.objects.get(pk=id)
            form = formRepository(request.POST, instance=updateRepository)

        if form.is_valid():
            form.save()
            context = {
                'namaMethod': 'formCrudRepository(else)'
            }
        return redirect('repositoryList/')


def repositoryDelete(request, id):
    deleteRepository = catalog.objects.get(pk=id)
    deleteRepository.delete()
    return redirect('repositoryList/')

admin_perpus/templates/admin_perpus/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Perpustakaan</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">
</head>

<body>
    <div class="container"> 
        <div class="col-md-10 offset-md-1 mt-5">
            <div class="jumbotron">

                {% block headCrud %}
                {% endblock headCrud %}
                
                {% block content %}
                {% endblock content %}
                
            </div>
        </div>
            
    </div>



    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

admin_perpus/templates/admin_perpus/formCrudCatalog.html
{% extends "admin_perpus/base.html" %}
{% load crispy_forms_tags %}

{% block headCrud%}
    <h1 class="display-4">Catalog</h1>
    <p class="lead font-italic">Laman khusus Admin Perpustakaan Uhamka</p>
    <p>nama method {{namaMethod}}</p>
    <hr class="my-4">
{% endblock %}

{% block content %}
<!-- action = kalau submitnya diclick, datanya mau disimpen kemana?
     action -> - ngga diisi, maka datanya akan disimpan di url tersebut
     action -> kalau diisi, maka datanya akan disimpan di url tujuan 
    -->
     
<form action="" method="POST" autocomplete="off">
    {% csrf_token %}
    
    {{form.lokasi | as_crispy_field}}
   
    {{form.judul | as_crispy_field}} 
    
    {{form.penulis | as_crispy_field}}

    {{form.katalog_jurusan | as_crispy_field}}

    {{form.keyword | as_crispy_field}}

    {{form.jumlah_buku | as_crispy_field}}

    {{form.bahasa | as_crispy_field}}
       
    <div style="display: flex; flex-direction: column;">
        <div class="col-md-8">
            <button type="submit" class="btn btn-success" style="margin: 10px;"><i class="fas fa-database" ></i> Submit</button>
        </div>
        <div class="col-md-4">
            <a href="{% url 'catalogList' %}" class="btn btn-secondary btn-block btn-lg">
                <i class="fas fa-stream"></i> Back to list
            </a>
        </div>
        <button type="" class="btn btn-success" style="margin: 10px;">
            <a href="{% url 'admin_perpus:pilihanCrud' %}" style="color: white;">Kembali</a></button>
    </div>

</form>
{% endblock content %}

admin_perpus/templates/admin_perpus/formCrudCatalogList.html
{% extends "admin_perpus/base.html" %}
{% load crispy_forms_tags %}

{% block headCrud%}
    <h1 class="display-4">Catalog List</h1>
    <p class="lead font-italic">Laman khusus Admin Perpustakaan Uhamka</p>
    <p>welcome: {{kata}}</p>
    <p>kartu ucapan: {{kartu_ucapan}}</p>
    {% if pesan %}
        <p>isi dari database {{pesan}}</p>
    {% endif %}

    <hr class="my-4">
{% endblock %}

{% block content %}

{% if pesan %}
    <p>isi dari database {{pesan}}</p>
{% endif %}

<table class="table table-borderless">
    <thead class="border-bottom font-weight-bold">
        <tr>
            <td>keyword</td>
            <td>judul</td>
            <td>penulis</td>
            <td></td>
        </tr>
    </thead>
    <tbody>
        {% for katalog in catalog_list %}
            <tr>
                <td>{{katalog.keyword}}</td>
                <td>{{katalog.judul}}</td>
                <td>{{katalog.penulis}}</td>
                <td>
                    <a href="{% url 'formCrudCatalogUpdate' formCrudCatalog.id %}" class="btn text-secondary px-0">
                        <i class="far fa-edit fa-lg"></i>
                    </a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

admin_perpus/templates/admin_perpus/formCrudJournal.html
{% extends "admin_perpus/base.html" %}
{% load crispy_forms_tags %}

{% block headCrud%}
    <h1 class="display-4">Jurnal</h1>
    <p class="lead font-italic">Laman khusus Admin Perpustakaan Uhamka</p>
    <p>nama mehtod {{namaMethod}}</p>
    <hr class="my-4">
{% endblock %}

{% block content %}

<!-- action = kalau submitnya diclick, datanya mau disimpen kemana?
     action -> - ngga diisi, maka datanya akan disimpan di url tersebut
     action -> kalau diisi, maka datanya akan disimpan di url tujuan -->
     
<form action="" method="POST" autocomplete="off">
    {% csrf_token %}

    {{form.judul_artikel  | as_crispy_field}}

    {{form.judul_terbitan | as_crispy_field}}
   
    {{form.issn | as_crispy_field}}
   
    {{form.bahasa | as_crispy_field}}
    
    {{form.tempat_terbit | as_crispy_field}}
    
    {{form.tahun | as_crispy_field}}

    {{form.volume | as_crispy_field}}
    
    {{form.penerbit | as_crispy_field }}

    {{form.frekuensi_penerbitan | as_crispy_field}}

    {{form.penulis | as_crispy_field}}
    
    <!-- {{form.abstaksi }}
   
    {{form.kata_kunci }}
    
    {{form.lokasi }}
    
    {{form.terakreditasi }}
    
    {{form.slug }}
     -->
    <div style="display: flex; flex-direction: column;">
        <div class="col-md-8">
            <button type="submit" class="btn btn-success" style="margin: 10px;"><i class="fas fa-database" ></i> Submit</button>
        </div>
        <div class="col-md-4">
            <a href="{% url 'jurnalList' %}" class="btn btn-secondary btn-block btn-lg">
                <i class="fas fa-stream"></i> Back to list
            </a>
        </div>
        <button type="" class="btn btn-success" >
            <a href="{% url 'admin_perpus:pilihanCrud' %}" style="color: white;">Kembali</a></button>
    </div>

</form>
{% endblock content %}

admin_perpus/templates/admin_perpus/formCrudRepository.html
{% extends "admin_perpus/base.html" %}
{% load crispy_forms_tags %}

{% block headCrud%}
    <h1 class="display-4">Repository</h1>
    <p class="lead font-italic">Laman khusus Admin Perpustakaan Uhamka</p>
    <hr class="my-4">
{% endblock %}

{% block content %}

<!-- action = kalau submitnya diclick, datanya mau disimpen kemana?
     action -> - ngga diisi, maka datanya akan disimpan di url tersebut
     action -> kalau diisi, maka datanya akan disimpan di url tujuan -->
     
<form action="" method="POST" autocomplete="off">
    {% csrf_token %}

    {{form.judul | as_crispy_field}}

    {{form.penulis | as_crispy_field}}
    
    {{form.abstraksi | as_crispy_field}}
   
    {{form.keyword | as_crispy_field}} 
    
    {{form.pembimbing | as_crispy_field}} 
    
    {{form.jenis_penulisan | as_crispy_field}} 

    {{form.lokasi | as_crispy_field}}

    <!-- <div class="form-group input-group my-3">
        <label for="">Judul Artikel : {{form.slug}} </label>
    </div> -->
    
       
  
    <div style="display: flex; flex-direction: column;">
        <div class="col-md-8">
            <button type="submit" class="btn btn-success" style="margin: 10px;"><i class="fas fa-database" ></i> Submit</button>
        </div>
        <div class="col-md-4">
            <a href="{% url 'repositoryList' %}" class="btn btn-secondary btn-block btn-lg">
                <i class="fas fa-stream"></i> Back to list
            </a>
        </div>
        <button type="" class="btn btn-success" >
            <a href="{% url 'admin_perpus:pilihanCrud' %}" style="color: white;">Kembali</a></button>
    </div>

</form>
{% endblock content %}

admin_perpus/templates/admin_perpus/listCatalog.html
{% extends "admin_perpus/base.html" %}
{% load crispy_forms_tags %}

{% block headCrud%}
    <h1 class="display-4">Catalog List</h1>
    <p class="lead font-italic">Laman khusus Admin Perpustakaan Uhamka</p>
    <p>welcome: {{greeting}}</p>
    <hr class="my-4">
{% endblock %}

{% block content %}

<table class="table table-borderless">
    <thead class="border-bottom font-weight-bold">
        <tr>
            <td>keyword</td>
            <td>judul</td>
            <td>penulis</td>
            <td>
                <a href="{% url 'formCrudCatalog' %}" class="btn text-secondary px-0">
                    <i class="fas fa-plus"></i> Add New
            </td>
        </tr>
    </thead>
    <tbody>
        {% for katalog in catalog_list %}
            <tr>
                <td>{{katalog.keyword}}</td>
                <td>{{katalog.judul}}</td>
                <td>{{katalog.penulis}}</td>
                <td>
                    <a href="{% url 'formCrudCatalogUpdate' katalog.id %}" class="btn text-secondary px-0">
                        <i class="far fa-edit fa-lg"></i>
                    </a>
                    <form action="{% url 'catalogDelete' katalog.id %}" method="POST" class="d-inline">
                        {% csrf_token %}
                        <button class="btn">
                            <i class="far fa-trash-alt fa-lg text-danger float-right"></i>
                        </button>

                    </form>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

admin_perpus/templates/admin_perpus/listJurnal.html
{% extends "admin_perpus/base.html" %}
{% load crispy_forms_tags %}

{% block headCrud%}
    <h1 class="display-4">Journal List</h1>
    <p class="lead font-italic">Laman khusus Admin Perpustakaan Uhamka</p>
    <p>nama mehtod {{namaMethod}}</p>
    <hr class="my-4">
{% endblock %}

{% block content %}

<table class="table table-borderless">
    <thead class="border-bottom font-weight-bold">
        <tr>
            <td>issn</td>
            <td>judul</td>
            <td>penulis</td>
            <td>
                <a href="{% url 'formCrudJurnal' %}" class="btn text-secondary px-0">
                    <i class="fas fa-plus"></i> Add New
            </td>
        </tr>
    </thead>
    <tbody>
        {% for jurnal in jurnalList %}
            <tr>
                <td>{{jurnal.issn}}</td>
                <td>{{jurnal.judul}}</td>
                <td>{{jurnal.penulis}}</td>
                <td>
                    <a href="{% url 'formCrudJurnalUpdate' jurnal.id %}" class="btn text-secondary px-0">
                        <i class="far fa-edit fa-lg"></i>
                    </a>
                    <form action="{% url 'jurnalDelete' jurnal.id %}" method="POST" class="d-inline">
                        {% csrf_token %}
                        <button class="btn">
                            <i class="far fa-trash-alt fa-lg text-danger float-right"></i>
                        </button>

                    </form>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

admin_perpus/templates/admin_perpus/listRepository.html
{% extends "admin_perpus/base.html" %}
{% load crispy_forms_tags %}

{% block headCrud%}
    <h1 class="display-4">Repository List</h1>
    <p class="lead font-italic">Laman khusus Admin Perpustakaan Uhamka</p>
    <p>nama mehtod {{namaMethod}}</p>
    <hr class="my-4">
{% endblock %}

{% block content %}

<table class="table table-borderless">
    <thead class="border-bottom font-weight-bold">
        <tr>
            <td>keyword</td>
            <td>judul</td>
            <td>penulis</td>
            <td>
                <a href="{% url 'formCrudRepository' %}" class="btn text-secondary px-0">
                    <i class="fas fa-plus"></i> Add New
            </td>
        </tr>
    </thead>
    <tbody>
        {% for repository in repositoryList %}
            <tr>
                <td>{{repository.keyword}}</td>
                <td>{{repository.judul}}</td>
                <td>{{repository.penulis}}</td>
                <td>
                    <a href="{% url 'formCrudRepositoryUpdate' repository.id %}" class="btn text-secondary px-0">
                        <i class="far fa-edit fa-lg"></i>
                    </a>
                    <form action="{% url 'repositoryDelete' repository.id %}" method="POST" class="d-inline">
                        {% csrf_token %}
                        <button class="btn">
                            <i class="far fa-trash-alt fa-lg text-danger float-right"></i>
                        </button>

                    </form>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

admin_perpus/templates/admin_perpus/login.html
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'img/logo uhamka.png' %}">
    <title>{{title}}</title>
    <link rel="stylesheet" href="{% static 'css/style_admin_perpus.css' %}">
    <script src="https://kit.fontawesome.com/64d58efce2.js" crossorigin="anonymous"></script>
    

</head>
<body>
    <div class="container">

        <div class="forms-container">
          <div class="signin-signup">

            <form action="" method="POST" class="sign-in-form">
              {% csrf_token %}
              <h2 class="title">Masuk</h2>
              {{ form | crispy}} 
              <button type="submit" class="btn btn-success">Masuk</button>
              <p class="social-text">Laman ini dikhususkan untuk Admin Perpustakaan</p>
            </form>
  
            <form action="#" class="sign-up-form">
              <h2 class="title">Daftar</h2>
              <div class="input-field">
                <i class="fas fa-user"></i>
                <!-- form input nama sign up -->
             
              </div>
              <div class="input-field">
                <i class="fas fa-user"></i>
                <input type="email" placeholder="No Induk " />
              </div>
              
              <div class="input-field">
                <i class="fas fa-lock"></i>
                <input type="password" placeholder="Kata sandi" />
              </div>
              <input type="submit" class="btn" value="Daftar" />
              <p>Maaf Nomer Induk tidak tersedia</p>
            </form>
          </div>
        </div>
  
        <div class="panels-container" >
  
          <div class="panel left-panel">
            <div class="content">
              <h3>Perpustakaan Uhamka</h3>
              <!-- <p> Belum memiliki akun?</p>
              <button class="btn transparent" id="sign-up-btn">Daftar</button> -->
            </div>
            <img src="{% static 'img/logo_uhamka.png' %}" class="image" alt="" />
          </div>
  
          <div class="panel right-panel">
            <div class="content">
              <h3>Perpustakaan Uhamka</h3>
              <p> Apabila sudah memiliki akun, silakan masuk. </p>
              <button class="btn transparent" id="sign-in-btn">Masuk</button>
            </div>
            <img src="{% static 'img/logo_uhamka.png' %}" class="image" alt="" />
          </div>
        </div>
      </div>
      <script src="{% static 'js/app_admin_perpus.js' %}" type="text/javascript"></script>
</body>
</html>

admin_perpus/templates/admin_perpus/pilihanCrud.html
{% extends "admin_perpus/base.html" %}
{% load crispy_forms_tags %}

{% block headCrud%}
    <h1 class="display-4">Perpustakaan Uhamka </h1>
    <p class="lead font-italic">Laman khusus Admin Perpustakaan Uhamka</p>
    <p>ucapan selamat datang: {{ucapan}}</p>
    <hr class="my-4">
{% endblock %}

{% block content %}
    <div style="display: flex; flex-direction: column;">
        <button type="" class="btn btn-success" >
            <a href="{% url 'admin_perpus:formCrudCatalog' %}" style="color: white;">Catalog</a></button>
        <button type="" class="btn btn-success ">
            <a href="{% url 'admin_perpus:formCrudJurnal' %}" style="color: white;">Journal</a></button>
        <button type="" class="btn btn-success ">
            <a href="{% url 'admin_perpus:formCrudRepository' %}" style="color: white;">Repository</a></button>
    </div>


{% endblock content %}